format = "$custom$directory$git_branch$git_commit$git_status[➜ ](white)"
add_newline = false

[directory]
truncation_length = 1
truncation_symbol = "…"
format = "[$path](bold blue)"

[git_branch]
only_attached = true
format = "[\\(](white)[$branch](yellow)"

[git_commit]
only_detached = true
format = "[ \\(](white)[$hash](yellow)"

[git_status]
format = "$ahead_behind[\\)](white)$all_status"

ahead = "[↑${count}](bold cyan)"
behind = "[↓${count}](bold cyan)"
diverged = "[↑${ahead_count}↓${behind_count}](bold cyan)"

conflicted = "[𝝙 ](bold red)"
untracked = "[⚑ ](red)"
stashed = "[⬚ ](white)"
staged = "[♻ ](green)"
modified = "[♻ ](red)"
renamed = ""
deleted = "[✖ ](red)"

[custom.host_icon]
command = "echo $MY_HOST_ICON"
when = "true"
format = "[$output](white) "

[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
format = " 🕙 $duration($style) "
style = "bold italic #87A752"